// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// 	codegen	v0.0.0-SNAPSHOT-7397037
// 	go		go1.25.2
// source: core.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 0	-	100 	xerror包占用
// 100	-	1000	http status code
// 1000 -	2000	core 占用
// 2000 - 10000
type ErrCode int32

const (
	ErrCode_Success ErrCode = 0
	// 100	-	1000	http status code
	ErrCode_StatusContinue                      ErrCode = 100
	ErrCode_StatusSwitchingProtocols            ErrCode = 101
	ErrCode_StatusProcessing                    ErrCode = 102
	ErrCode_StatusEarlyHints                    ErrCode = 103
	ErrCode_StatusOK                            ErrCode = 200
	ErrCode_StatusCreated                       ErrCode = 201
	ErrCode_StatusAccepted                      ErrCode = 202
	ErrCode_StatusNonAuthoritativeInfo          ErrCode = 203
	ErrCode_StatusNoContent                     ErrCode = 204
	ErrCode_StatusResetContent                  ErrCode = 205
	ErrCode_StatusPartialContent                ErrCode = 206
	ErrCode_StatusMultiStatus                   ErrCode = 207
	ErrCode_StatusAlreadyReported               ErrCode = 208
	ErrCode_StatusIMUsed                        ErrCode = 226
	ErrCode_StatusMultipleChoices               ErrCode = 300
	ErrCode_StatusMovedPermanently              ErrCode = 301
	ErrCode_StatusFound                         ErrCode = 302
	ErrCode_StatusSeeOther                      ErrCode = 303
	ErrCode_StatusNotModified                   ErrCode = 304
	ErrCode_StatusUseProxy                      ErrCode = 305
	ErrCode_StatusTemporaryRedirect             ErrCode = 307
	ErrCode_StatusPermanentRedirect             ErrCode = 308
	ErrCode_StatusBadRequest                    ErrCode = 400
	ErrCode_StatusUnauthorized                  ErrCode = 401
	ErrCode_StatusPaymentRequired               ErrCode = 402
	ErrCode_StatusForbidden                     ErrCode = 403
	ErrCode_StatusNotFound                      ErrCode = 404
	ErrCode_StatusMethodNotAllowed              ErrCode = 405
	ErrCode_StatusNotAcceptable                 ErrCode = 406
	ErrCode_StatusProxyAuthRequired             ErrCode = 407
	ErrCode_StatusRequestTimeout                ErrCode = 408
	ErrCode_StatusConflict                      ErrCode = 409
	ErrCode_StatusGone                          ErrCode = 410
	ErrCode_StatusLengthRequired                ErrCode = 411
	ErrCode_StatusPreconditionFailed            ErrCode = 412
	ErrCode_StatusRequestEntityTooLarge         ErrCode = 413
	ErrCode_StatusRequestURITooLong             ErrCode = 414
	ErrCode_StatusUnsupportedMediaType          ErrCode = 415
	ErrCode_StatusRequestedRangeNotSatisfiable  ErrCode = 416
	ErrCode_StatusExpectationFailed             ErrCode = 417
	ErrCode_StatusTeapot                        ErrCode = 418
	ErrCode_StatusMisdirectedRequest            ErrCode = 421
	ErrCode_StatusUnprocessableEntity           ErrCode = 422
	ErrCode_StatusLocked                        ErrCode = 423
	ErrCode_StatusFailedDependency              ErrCode = 424
	ErrCode_StatusTooEarly                      ErrCode = 425
	ErrCode_StatusUpgradeRequired               ErrCode = 426
	ErrCode_StatusPreconditionRequired          ErrCode = 428
	ErrCode_StatusTooManyRequests               ErrCode = 429
	ErrCode_StatusRequestHeaderFieldsTooLarge   ErrCode = 431
	ErrCode_StatusUnavailableForLegalReasons    ErrCode = 451
	ErrCode_StatusInternalServerError           ErrCode = 500
	ErrCode_StatusNotImplemented                ErrCode = 501
	ErrCode_StatusBadGateway                    ErrCode = 502
	ErrCode_StatusServiceUnavailable            ErrCode = 503
	ErrCode_StatusGatewayTimeout                ErrCode = 504
	ErrCode_StatusHTTPVersionNotSupported       ErrCode = 505
	ErrCode_StatusVariantAlsoNegotiates         ErrCode = 506
	ErrCode_StatusInsufficientStorage           ErrCode = 507
	ErrCode_StatusLoopDetected                  ErrCode = 508
	ErrCode_StatusNotExtended                   ErrCode = 510
	ErrCode_StatusNetworkAuthenticationRequired ErrCode = 511
	// 1000 -	2000	core 占用
	ErrCode_ServerNotFound          ErrCode = 1000
	ErrCode_ServerNodeNotFound      ErrCode = 1001
	ErrCode_ServerAliveNodeNotFound ErrCode = 1002
	ErrCode_ConfigNotFound          ErrCode = 1003
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "Success",
		100:  "StatusContinue",
		101:  "StatusSwitchingProtocols",
		102:  "StatusProcessing",
		103:  "StatusEarlyHints",
		200:  "StatusOK",
		201:  "StatusCreated",
		202:  "StatusAccepted",
		203:  "StatusNonAuthoritativeInfo",
		204:  "StatusNoContent",
		205:  "StatusResetContent",
		206:  "StatusPartialContent",
		207:  "StatusMultiStatus",
		208:  "StatusAlreadyReported",
		226:  "StatusIMUsed",
		300:  "StatusMultipleChoices",
		301:  "StatusMovedPermanently",
		302:  "StatusFound",
		303:  "StatusSeeOther",
		304:  "StatusNotModified",
		305:  "StatusUseProxy",
		307:  "StatusTemporaryRedirect",
		308:  "StatusPermanentRedirect",
		400:  "StatusBadRequest",
		401:  "StatusUnauthorized",
		402:  "StatusPaymentRequired",
		403:  "StatusForbidden",
		404:  "StatusNotFound",
		405:  "StatusMethodNotAllowed",
		406:  "StatusNotAcceptable",
		407:  "StatusProxyAuthRequired",
		408:  "StatusRequestTimeout",
		409:  "StatusConflict",
		410:  "StatusGone",
		411:  "StatusLengthRequired",
		412:  "StatusPreconditionFailed",
		413:  "StatusRequestEntityTooLarge",
		414:  "StatusRequestURITooLong",
		415:  "StatusUnsupportedMediaType",
		416:  "StatusRequestedRangeNotSatisfiable",
		417:  "StatusExpectationFailed",
		418:  "StatusTeapot",
		421:  "StatusMisdirectedRequest",
		422:  "StatusUnprocessableEntity",
		423:  "StatusLocked",
		424:  "StatusFailedDependency",
		425:  "StatusTooEarly",
		426:  "StatusUpgradeRequired",
		428:  "StatusPreconditionRequired",
		429:  "StatusTooManyRequests",
		431:  "StatusRequestHeaderFieldsTooLarge",
		451:  "StatusUnavailableForLegalReasons",
		500:  "StatusInternalServerError",
		501:  "StatusNotImplemented",
		502:  "StatusBadGateway",
		503:  "StatusServiceUnavailable",
		504:  "StatusGatewayTimeout",
		505:  "StatusHTTPVersionNotSupported",
		506:  "StatusVariantAlsoNegotiates",
		507:  "StatusInsufficientStorage",
		508:  "StatusLoopDetected",
		510:  "StatusNotExtended",
		511:  "StatusNetworkAuthenticationRequired",
		1000: "ServerNotFound",
		1001: "ServerNodeNotFound",
		1002: "ServerAliveNodeNotFound",
		1003: "ConfigNotFound",
	}
	ErrCode_value = map[string]int32{
		"Success":                             0,
		"StatusContinue":                      100,
		"StatusSwitchingProtocols":            101,
		"StatusProcessing":                    102,
		"StatusEarlyHints":                    103,
		"StatusOK":                            200,
		"StatusCreated":                       201,
		"StatusAccepted":                      202,
		"StatusNonAuthoritativeInfo":          203,
		"StatusNoContent":                     204,
		"StatusResetContent":                  205,
		"StatusPartialContent":                206,
		"StatusMultiStatus":                   207,
		"StatusAlreadyReported":               208,
		"StatusIMUsed":                        226,
		"StatusMultipleChoices":               300,
		"StatusMovedPermanently":              301,
		"StatusFound":                         302,
		"StatusSeeOther":                      303,
		"StatusNotModified":                   304,
		"StatusUseProxy":                      305,
		"StatusTemporaryRedirect":             307,
		"StatusPermanentRedirect":             308,
		"StatusBadRequest":                    400,
		"StatusUnauthorized":                  401,
		"StatusPaymentRequired":               402,
		"StatusForbidden":                     403,
		"StatusNotFound":                      404,
		"StatusMethodNotAllowed":              405,
		"StatusNotAcceptable":                 406,
		"StatusProxyAuthRequired":             407,
		"StatusRequestTimeout":                408,
		"StatusConflict":                      409,
		"StatusGone":                          410,
		"StatusLengthRequired":                411,
		"StatusPreconditionFailed":            412,
		"StatusRequestEntityTooLarge":         413,
		"StatusRequestURITooLong":             414,
		"StatusUnsupportedMediaType":          415,
		"StatusRequestedRangeNotSatisfiable":  416,
		"StatusExpectationFailed":             417,
		"StatusTeapot":                        418,
		"StatusMisdirectedRequest":            421,
		"StatusUnprocessableEntity":           422,
		"StatusLocked":                        423,
		"StatusFailedDependency":              424,
		"StatusTooEarly":                      425,
		"StatusUpgradeRequired":               426,
		"StatusPreconditionRequired":          428,
		"StatusTooManyRequests":               429,
		"StatusRequestHeaderFieldsTooLarge":   431,
		"StatusUnavailableForLegalReasons":    451,
		"StatusInternalServerError":           500,
		"StatusNotImplemented":                501,
		"StatusBadGateway":                    502,
		"StatusServiceUnavailable":            503,
		"StatusGatewayTimeout":                504,
		"StatusHTTPVersionNotSupported":       505,
		"StatusVariantAlsoNegotiates":         506,
		"StatusInsufficientStorage":           507,
		"StatusLoopDetected":                  508,
		"StatusNotExtended":                   510,
		"StatusNetworkAuthenticationRequired": 511,
		"ServerNotFound":                      1000,
		"ServerNodeNotFound":                  1001,
		"ServerAliveNodeNotFound":             1002,
		"ConfigNotFound":                      1003,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

type DiscoveryType int32

const (
	DiscoveryType_Lazy   DiscoveryType = 0
	DiscoveryType_Etcd   DiscoveryType = 1
	DiscoveryType_Consul DiscoveryType = 2
	DiscoveryType_Nacos  DiscoveryType = 3
)

// Enum value maps for DiscoveryType.
var (
	DiscoveryType_name = map[int32]string{
		0: "Lazy",
		1: "Etcd",
		2: "Consul",
		3: "Nacos",
	}
	DiscoveryType_value = map[string]int32{
		"Lazy":   0,
		"Etcd":   1,
		"Consul": 2,
		"Nacos":  3,
	}
)

func (x DiscoveryType) Enum() *DiscoveryType {
	p := new(DiscoveryType)
	*p = x
	return p
}

func (x DiscoveryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoveryType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[1].Descriptor()
}

func (DiscoveryType) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[1]
}

func (x DiscoveryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoveryType.Descriptor instead.
func (DiscoveryType) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

type ServiceType int32

const (
	ServiceType_Service ServiceType = 0
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "Service",
	}
	ServiceType_value = map[string]int32{
		"Service": 0,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_enumTypes[2].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_core_proto_enumTypes[2]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" toml:"code,omitempty" gorm:"column:code;not null;default:0" yaml:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" yaml:"message,omitempty" toml:"message,omitempty" gorm:"default:'';column:message;type:varchar(255);not null"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty" yaml:"data,omitempty" toml:"data,omitempty" gorm:"column:data"`
	Hint          string                 `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty" yaml:"hint,omitempty" toml:"hint,omitempty" gorm:"default:'';column:hint;type:varchar(255);not null"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BaseResponse) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type RawReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty" gorm:"type:json;serializer:json;column:body" yaml:"body,omitempty" toml:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawReq) Reset() {
	*x = RawReq{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawReq) ProtoMessage() {}

func (x *RawReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawReq.ProtoReflect.Descriptor instead.
func (*RawReq) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *RawReq) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type RawRsp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Body  []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty" toml:"body,omitempty" gorm:"type:json;serializer:json;column:body" yaml:"body,omitempty"`
	// 不填会按照纯文本处理
	ContentType   string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty" yaml:"content_type,omitempty" toml:"content_type,omitempty" gorm:"type:varchar(255);not null;default:'';column:content_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawRsp) Reset() {
	*x = RawRsp{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawRsp) ProtoMessage() {}

func (x *RawRsp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawRsp.ProtoReflect.Descriptor instead.
func (*RawRsp) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *RawRsp) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RawRsp) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ServiceDiscoveryClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiscoveryType DiscoveryType          `protobuf:"varint,1,opt,name=discovery_type,json=discoveryType,proto3,enum=lazygophers.lrpc.core.DiscoveryType" json:"discovery_type,omitempty" yaml:"discovery_type,omitempty" toml:"discovery_type,omitempty" gorm:"not null;default:0;column:discovery_type"`
	// 当 type = none 时生效
	Url           []string             `protobuf:"bytes,2,rep,name=url,proto3" json:"url,omitempty" yaml:"url,omitempty" toml:"url,omitempty" gorm:"serializer:json;column:url;type:json"`
	ServiceName   string               `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty" yaml:"service_name,omitempty" toml:"service_name,omitempty" gorm:"not null;default:'';column:service_name;type:varchar(255)"`
	ServicePath   string               `protobuf:"bytes,4,opt,name=service_path,json=servicePath,proto3" json:"service_path,omitempty" toml:"service_path,omitempty" gorm:"default:'';column:service_path;type:varchar(255);not null" yaml:"service_path,omitempty"`
	Method        string               `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty" yaml:"method,omitempty" toml:"method,omitempty" gorm:"type:varchar(255);not null;default:'';column:method"`
	Timeout       *durationpb.Duration `protobuf:"bytes,6,opt,name=timeout,proto3" json:"timeout,omitempty" gorm:"column:timeout" yaml:"timeout,omitempty" toml:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDiscoveryClient) Reset() {
	*x = ServiceDiscoveryClient{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDiscoveryClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscoveryClient) ProtoMessage() {}

func (x *ServiceDiscoveryClient) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscoveryClient.ProtoReflect.Descriptor instead.
func (*ServiceDiscoveryClient) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceDiscoveryClient) GetDiscoveryType() DiscoveryType {
	if x != nil {
		return x.DiscoveryType
	}
	return DiscoveryType_Lazy
}

func (x *ServiceDiscoveryClient) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *ServiceDiscoveryClient) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceDiscoveryClient) GetServicePath() string {
	if x != nil {
		return x.ServicePath
	}
	return ""
}

func (x *ServiceDiscoveryClient) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ServiceDiscoveryClient) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type ServiceDiscoveryService struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ServiceName   string                  `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty" toml:"service_name,omitempty" gorm:"not null;default:'';column:service_name;type:varchar(255)" yaml:"service_name,omitempty"`
	NodeList      []*ServiceDiscoveryNode `protobuf:"bytes,2,rep,name=node_list,json=nodeList,proto3" json:"node_list,omitempty" yaml:"node_list,omitempty" toml:"node_list,omitempty" gorm:"column:node_list;type:json;serializer:json"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDiscoveryService) Reset() {
	*x = ServiceDiscoveryService{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDiscoveryService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscoveryService) ProtoMessage() {}

func (x *ServiceDiscoveryService) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscoveryService.ProtoReflect.Descriptor instead.
func (*ServiceDiscoveryService) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceDiscoveryService) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceDiscoveryService) GetNodeList() []*ServiceDiscoveryNode {
	if x != nil {
		return x.NodeList
	}
	return nil
}

type ServiceDiscoveryNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ServiceType            `protobuf:"varint,1,opt,name=type,proto3,enum=lazygophers.lrpc.core.ServiceType" json:"type,omitempty" yaml:"type,omitempty" toml:"type,omitempty" gorm:"not null;default:0;column:type"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty" yaml:"host,omitempty" toml:"host,omitempty" gorm:"type:varchar(255);not null;default:'';column:host"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty" yaml:"port,omitempty" toml:"port,omitempty" gorm:"default:'';column:port;type:varchar(255);not null"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty" yaml:"username,omitempty" toml:"username,omitempty" gorm:"column:username;type:varchar(255);not null;default:''"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty" yaml:"password,omitempty" toml:"password,omitempty" gorm:"default:'';column:password;type:varchar(255);not null"`
	Alive         bool                   `protobuf:"varint,6,opt,name=alive,proto3" json:"alive,omitempty" yaml:"alive,omitempty" toml:"alive,omitempty" gorm:"default:0;not null;type:tinyint(1);column:alive"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDiscoveryNode) Reset() {
	*x = ServiceDiscoveryNode{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDiscoveryNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscoveryNode) ProtoMessage() {}

func (x *ServiceDiscoveryNode) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscoveryNode.ProtoReflect.Descriptor instead.
func (*ServiceDiscoveryNode) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceDiscoveryNode) GetType() ServiceType {
	if x != nil {
		return x.Type
	}
	return ServiceType_Service
}

func (x *ServiceDiscoveryNode) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServiceDiscoveryNode) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ServiceDiscoveryNode) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ServiceDiscoveryNode) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ServiceDiscoveryNode) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

// 分布式配置
type ConfigItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty" toml:"key,omitempty" gorm:"type:varchar(255);not null;default:'';column:key" yaml:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" yaml:"value,omitempty" toml:"value,omitempty" gorm:"type:json;serializer:json;column:value"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty" yaml:"version,omitempty" toml:"version,omitempty" gorm:"not null;default:0;column:version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItem) Reset() {
	*x = ConfigItem{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItem) ProtoMessage() {}

func (x *ConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItem.ProtoReflect.Descriptor instead.
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigItem) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// 分页
type ListOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" gorm:"not null;default:0;column:offset" yaml:"offset,omitempty" toml:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" yaml:"limit,omitempty" toml:"limit,omitempty" gorm:"not null;default:0;column:limit"`
	ShowTotal     bool                   `protobuf:"varint,3,opt,name=show_total,json=showTotal,proto3" json:"show_total,omitempty" yaml:"show_total,omitempty" toml:"show_total,omitempty" gorm:"default:0;not null;type:tinyint(1);column:show_total"`
	Options       []*ListOption_Option   `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" yaml:"options,omitempty" toml:"options,omitempty" gorm:"type:json;serializer:json;column:options"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOption) Reset() {
	*x = ListOption{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOption) ProtoMessage() {}

func (x *ListOption) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOption.ProtoReflect.Descriptor instead.
func (*ListOption) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *ListOption) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListOption) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOption) GetShowTotal() bool {
	if x != nil {
		return x.ShowTotal
	}
	return false
}

func (x *ListOption) GetOptions() []*ListOption_Option {
	if x != nil {
		return x.Options
	}
	return nil
}

type Paginate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" yaml:"offset,omitempty" toml:"offset,omitempty" gorm:"not null;default:0;column:offset"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" toml:"limit,omitempty" gorm:"default:0;column:limit;not null" yaml:"limit,omitempty"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty" yaml:"total,omitempty" toml:"total,omitempty" gorm:"default:0;column:total;not null"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paginate) Reset() {
	*x = Paginate{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paginate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paginate) ProtoMessage() {}

func (x *Paginate) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paginate.ProtoReflect.Descriptor instead.
func (*Paginate) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *Paginate) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Paginate) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Paginate) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 代码生成
type Http struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        *string                `protobuf:"bytes,1,opt,name=method,proto3,oneof" json:"method,omitempty" gorm:"serializer:json;column:method;type:json" yaml:"method,omitempty" toml:"method,omitempty"`
	Path          *string                `protobuf:"bytes,2,opt,name=path,proto3,oneof" json:"path,omitempty" yaml:"path,omitempty" toml:"path,omitempty" gorm:"column:path;type:json;serializer:json"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Http) Reset() {
	*x = Http{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http) ProtoMessage() {}

func (x *Http) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Http.ProtoReflect.Descriptor instead.
func (*Http) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *Http) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

func (x *Http) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type LazyGen struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoleList       []string               `protobuf:"bytes,1,rep,name=role_list,json=roleList,proto3" json:"role_list,omitempty" yaml:"role_list,omitempty" toml:"role_list,omitempty" gorm:"type:json;serializer:json;column:role_list"`                                     // 角色，如 admin/user/public 等
	GenTo          string                 `protobuf:"bytes,2,opt,name=gen_to,json=genTo,proto3" json:"gen_to,omitempty" yaml:"gen_to,omitempty" toml:"gen_to,omitempty" gorm:"type:varchar(255);not null;default:'';column:gen_to"`                                           // 生成到的文件名，默认使用 impl
	BeforeHandlers []string               `protobuf:"bytes,3,rep,name=before_handlers,json=beforeHandlers,proto3" json:"before_handlers,omitempty" yaml:"before_handlers,omitempty" toml:"before_handlers,omitempty" gorm:"type:json;serializer:json;column:before_handlers"` // 前置拦截器
	AfterHandlers  []string               `protobuf:"bytes,4,rep,name=after_handlers,json=afterHandlers,proto3" json:"after_handlers,omitempty" gorm:"type:json;serializer:json;column:after_handlers" yaml:"after_handlers,omitempty" toml:"after_handlers,omitempty"`       // 后置拦截器
	Group          string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty" gorm:"column:group;type:varchar(255);not null;default:''" yaml:"group,omitempty" toml:"group,omitempty"`                                                           // 分组
	Desc           string                 `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty" yaml:"desc,omitempty" toml:"desc,omitempty" gorm:"column:desc;type:varchar(255);not null;default:''"`                                                                // 接口描述
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LazyGen) Reset() {
	*x = LazyGen{}
	mi := &file_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LazyGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LazyGen) ProtoMessage() {}

func (x *LazyGen) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LazyGen.ProtoReflect.Descriptor instead.
func (*LazyGen) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10}
}

func (x *LazyGen) GetRoleList() []string {
	if x != nil {
		return x.RoleList
	}
	return nil
}

func (x *LazyGen) GetGenTo() string {
	if x != nil {
		return x.GenTo
	}
	return ""
}

func (x *LazyGen) GetBeforeHandlers() []string {
	if x != nil {
		return x.BeforeHandlers
	}
	return nil
}

func (x *LazyGen) GetAfterHandlers() []string {
	if x != nil {
		return x.AfterHandlers
	}
	return nil
}

func (x *LazyGen) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *LazyGen) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type ListOption_Option struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty" yaml:"key,omitempty" toml:"key,omitempty" gorm:"not null;default:0;column:key"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" yaml:"value,omitempty" toml:"value,omitempty" gorm:"column:value;type:varchar(255);not null;default:''"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOption_Option) Reset() {
	*x = ListOption_Option{}
	mi := &file_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOption_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOption_Option) ProtoMessage() {}

func (x *ListOption_Option) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOption_Option.ProtoReflect.Descriptor instead.
func (*ListOption_Option) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListOption_Option) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ListOption_Option) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var file_core_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Http)(nil),
		Field:         60000,
		Name:          "lazygophers.lrpc.core.http",
		Tag:           "bytes,60000,opt,name=http",
		Filename:      "core.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*LazyGen)(nil),
		Field:         60001,
		Name:          "lazygophers.lrpc.core.lazygen",
		Tag:           "bytes,60001,opt,name=lazygen",
		Filename:      "core.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         60000,
		Name:          "lazygophers.lrpc.core.port",
		Tag:           "varint,60000,opt,name=port",
		Filename:      "core.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         60001,
		Name:          "lazygophers.lrpc.core.host",
		Tag:           "bytes,60001,opt,name=host",
		Filename:      "core.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional lazygophers.lrpc.core.Http http = 60000;
	E_Http = &file_core_proto_extTypes[0]
	// optional lazygophers.lrpc.core.LazyGen lazygen = 60001;
	E_Lazygen = &file_core_proto_extTypes[1]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional int32 port = 60000;
	E_Port = &file_core_proto_extTypes[2]
	// 指定 ip
	// local/localhostt(相当于 127.0.0.1)
	// lan 内网 ip
	// */all （相当于 0.0.0.0）默认为这个
	//
	// optional string host = 60001;
	E_Host = &file_core_proto_extTypes[3]
)

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x15lazygophers.lrpc.core\x1a google/protobuf/descriptor.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\"z\n" +
	"\fBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\"\x1c\n" +
	"\x06RawReq\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\"?\n" +
	"\x06RawRsp\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"\x8a\x02\n" +
	"\x16ServiceDiscoveryClient\x12K\n" +
	"\x0ediscovery_type\x18\x01 \x01(\x0e2$.lazygophers.lrpc.core.DiscoveryTypeR\rdiscoveryType\x12\x10\n" +
	"\x03url\x18\x02 \x03(\tR\x03url\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_path\x18\x04 \x01(\tR\vservicePath\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x123\n" +
	"\atimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x86\x01\n" +
	"\x17ServiceDiscoveryService\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12H\n" +
	"\tnode_list\x18\x02 \x03(\v2+.lazygophers.lrpc.core.ServiceDiscoveryNodeR\bnodeList\"\xc4\x01\n" +
	"\x14ServiceDiscoveryNode\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".lazygophers.lrpc.core.ServiceTypeR\x04type\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x14\n" +
	"\x05alive\x18\x06 \x01(\bR\x05alive\"N\n" +
	"\n" +
	"ConfigItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\xcf\x01\n" +
	"\n" +
	"ListOption\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x1d\n" +
	"\n" +
	"show_total\x18\x03 \x01(\bR\tshowTotal\x12B\n" +
	"\aoptions\x18\x04 \x03(\v2(.lazygophers.lrpc.core.ListOption.OptionR\aoptions\x1a0\n" +
	"\x06Option\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"N\n" +
	"\bPaginate\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\"P\n" +
	"\x04Http\x12\x1b\n" +
	"\x06method\x18\x01 \x01(\tH\x00R\x06method\x88\x01\x01\x12\x17\n" +
	"\x04path\x18\x02 \x01(\tH\x01R\x04path\x88\x01\x01B\t\n" +
	"\a_methodB\a\n" +
	"\x05_path\"\xb7\x01\n" +
	"\aLazyGen\x12\x1b\n" +
	"\trole_list\x18\x01 \x03(\tR\broleList\x12\x15\n" +
	"\x06gen_to\x18\x02 \x01(\tR\x05genTo\x12'\n" +
	"\x0fbefore_handlers\x18\x03 \x03(\tR\x0ebeforeHandlers\x12%\n" +
	"\x0eafter_handlers\x18\x04 \x03(\tR\rafterHandlers\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc*\x83\x0e\n" +
	"\aErrCode\x12\v\n" +
	"\aSuccess\x10\x00\x12\x12\n" +
	"\x0eStatusContinue\x10d\x12\x1c\n" +
	"\x18StatusSwitchingProtocols\x10e\x12\x14\n" +
	"\x10StatusProcessing\x10f\x12\x14\n" +
	"\x10StatusEarlyHints\x10g\x12\r\n" +
	"\bStatusOK\x10\xc8\x01\x12\x12\n" +
	"\rStatusCreated\x10\xc9\x01\x12\x13\n" +
	"\x0eStatusAccepted\x10\xca\x01\x12\x1f\n" +
	"\x1aStatusNonAuthoritativeInfo\x10\xcb\x01\x12\x14\n" +
	"\x0fStatusNoContent\x10\xcc\x01\x12\x17\n" +
	"\x12StatusResetContent\x10\xcd\x01\x12\x19\n" +
	"\x14StatusPartialContent\x10\xce\x01\x12\x16\n" +
	"\x11StatusMultiStatus\x10\xcf\x01\x12\x1a\n" +
	"\x15StatusAlreadyReported\x10\xd0\x01\x12\x11\n" +
	"\fStatusIMUsed\x10\xe2\x01\x12\x1a\n" +
	"\x15StatusMultipleChoices\x10\xac\x02\x12\x1b\n" +
	"\x16StatusMovedPermanently\x10\xad\x02\x12\x10\n" +
	"\vStatusFound\x10\xae\x02\x12\x13\n" +
	"\x0eStatusSeeOther\x10\xaf\x02\x12\x16\n" +
	"\x11StatusNotModified\x10\xb0\x02\x12\x13\n" +
	"\x0eStatusUseProxy\x10\xb1\x02\x12\x1c\n" +
	"\x17StatusTemporaryRedirect\x10\xb3\x02\x12\x1c\n" +
	"\x17StatusPermanentRedirect\x10\xb4\x02\x12\x15\n" +
	"\x10StatusBadRequest\x10\x90\x03\x12\x17\n" +
	"\x12StatusUnauthorized\x10\x91\x03\x12\x1a\n" +
	"\x15StatusPaymentRequired\x10\x92\x03\x12\x14\n" +
	"\x0fStatusForbidden\x10\x93\x03\x12\x13\n" +
	"\x0eStatusNotFound\x10\x94\x03\x12\x1b\n" +
	"\x16StatusMethodNotAllowed\x10\x95\x03\x12\x18\n" +
	"\x13StatusNotAcceptable\x10\x96\x03\x12\x1c\n" +
	"\x17StatusProxyAuthRequired\x10\x97\x03\x12\x19\n" +
	"\x14StatusRequestTimeout\x10\x98\x03\x12\x13\n" +
	"\x0eStatusConflict\x10\x99\x03\x12\x0f\n" +
	"\n" +
	"StatusGone\x10\x9a\x03\x12\x19\n" +
	"\x14StatusLengthRequired\x10\x9b\x03\x12\x1d\n" +
	"\x18StatusPreconditionFailed\x10\x9c\x03\x12 \n" +
	"\x1bStatusRequestEntityTooLarge\x10\x9d\x03\x12\x1c\n" +
	"\x17StatusRequestURITooLong\x10\x9e\x03\x12\x1f\n" +
	"\x1aStatusUnsupportedMediaType\x10\x9f\x03\x12'\n" +
	"\"StatusRequestedRangeNotSatisfiable\x10\xa0\x03\x12\x1c\n" +
	"\x17StatusExpectationFailed\x10\xa1\x03\x12\x11\n" +
	"\fStatusTeapot\x10\xa2\x03\x12\x1d\n" +
	"\x18StatusMisdirectedRequest\x10\xa5\x03\x12\x1e\n" +
	"\x19StatusUnprocessableEntity\x10\xa6\x03\x12\x11\n" +
	"\fStatusLocked\x10\xa7\x03\x12\x1b\n" +
	"\x16StatusFailedDependency\x10\xa8\x03\x12\x13\n" +
	"\x0eStatusTooEarly\x10\xa9\x03\x12\x1a\n" +
	"\x15StatusUpgradeRequired\x10\xaa\x03\x12\x1f\n" +
	"\x1aStatusPreconditionRequired\x10\xac\x03\x12\x1a\n" +
	"\x15StatusTooManyRequests\x10\xad\x03\x12&\n" +
	"!StatusRequestHeaderFieldsTooLarge\x10\xaf\x03\x12%\n" +
	" StatusUnavailableForLegalReasons\x10\xc3\x03\x12\x1e\n" +
	"\x19StatusInternalServerError\x10\xf4\x03\x12\x19\n" +
	"\x14StatusNotImplemented\x10\xf5\x03\x12\x15\n" +
	"\x10StatusBadGateway\x10\xf6\x03\x12\x1d\n" +
	"\x18StatusServiceUnavailable\x10\xf7\x03\x12\x19\n" +
	"\x14StatusGatewayTimeout\x10\xf8\x03\x12\"\n" +
	"\x1dStatusHTTPVersionNotSupported\x10\xf9\x03\x12 \n" +
	"\x1bStatusVariantAlsoNegotiates\x10\xfa\x03\x12\x1e\n" +
	"\x19StatusInsufficientStorage\x10\xfb\x03\x12\x17\n" +
	"\x12StatusLoopDetected\x10\xfc\x03\x12\x16\n" +
	"\x11StatusNotExtended\x10\xfe\x03\x12(\n" +
	"#StatusNetworkAuthenticationRequired\x10\xff\x03\x12\x13\n" +
	"\x0eServerNotFound\x10\xe8\a\x12\x17\n" +
	"\x12ServerNodeNotFound\x10\xe9\a\x12\x1c\n" +
	"\x17ServerAliveNodeNotFound\x10\xea\a\x12\x13\n" +
	"\x0eConfigNotFound\x10\xeb\a*:\n" +
	"\rDiscoveryType\x12\b\n" +
	"\x04Lazy\x10\x00\x12\b\n" +
	"\x04Etcd\x10\x01\x12\n" +
	"\n" +
	"\x06Consul\x10\x02\x12\t\n" +
	"\x05Nacos\x10\x03*\x1a\n" +
	"\vServiceType\x12\v\n" +
	"\aService\x10\x00:T\n" +
	"\x04http\x12\x1e.google.protobuf.MethodOptions\x18\xe0\xd4\x03 \x01(\v2\x1b.lazygophers.lrpc.core.HttpR\x04http\x88\x01\x01:]\n" +
	"\alazygen\x12\x1e.google.protobuf.MethodOptions\x18\xe1\xd4\x03 \x01(\v2\x1e.lazygophers.lrpc.core.LazyGenR\alazygen\x88\x01\x01:5\n" +
	"\x04port\x12\x1c.google.protobuf.FileOptions\x18\xe0\xd4\x03 \x01(\x05R\x04port\x88\x01\x01:5\n" +
	"\x04host\x12\x1c.google.protobuf.FileOptions\x18\xe1\xd4\x03 \x01(\tR\x04host\x88\x01\x01B0Z+github.com/lazygophers/lrpc/middleware/core\xf8\x01\x01b\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_core_proto_goTypes = []any{
	(ErrCode)(0),                       // 0: lazygophers.lrpc.core.ErrCode
	(DiscoveryType)(0),                 // 1: lazygophers.lrpc.core.DiscoveryType
	(ServiceType)(0),                   // 2: lazygophers.lrpc.core.ServiceType
	(*BaseResponse)(nil),               // 3: lazygophers.lrpc.core.BaseResponse
	(*RawReq)(nil),                     // 4: lazygophers.lrpc.core.RawReq
	(*RawRsp)(nil),                     // 5: lazygophers.lrpc.core.RawRsp
	(*ServiceDiscoveryClient)(nil),     // 6: lazygophers.lrpc.core.ServiceDiscoveryClient
	(*ServiceDiscoveryService)(nil),    // 7: lazygophers.lrpc.core.ServiceDiscoveryService
	(*ServiceDiscoveryNode)(nil),       // 8: lazygophers.lrpc.core.ServiceDiscoveryNode
	(*ConfigItem)(nil),                 // 9: lazygophers.lrpc.core.ConfigItem
	(*ListOption)(nil),                 // 10: lazygophers.lrpc.core.ListOption
	(*Paginate)(nil),                   // 11: lazygophers.lrpc.core.Paginate
	(*Http)(nil),                       // 12: lazygophers.lrpc.core.Http
	(*LazyGen)(nil),                    // 13: lazygophers.lrpc.core.LazyGen
	(*ListOption_Option)(nil),          // 14: lazygophers.lrpc.core.ListOption.Option
	(*anypb.Any)(nil),                  // 15: google.protobuf.Any
	(*durationpb.Duration)(nil),        // 16: google.protobuf.Duration
	(*descriptorpb.MethodOptions)(nil), // 17: google.protobuf.MethodOptions
	(*descriptorpb.FileOptions)(nil),   // 18: google.protobuf.FileOptions
}
var file_core_proto_depIdxs = []int32{
	15, // 0: lazygophers.lrpc.core.BaseResponse.data:type_name -> google.protobuf.Any
	1,  // 1: lazygophers.lrpc.core.ServiceDiscoveryClient.discovery_type:type_name -> lazygophers.lrpc.core.DiscoveryType
	16, // 2: lazygophers.lrpc.core.ServiceDiscoveryClient.timeout:type_name -> google.protobuf.Duration
	8,  // 3: lazygophers.lrpc.core.ServiceDiscoveryService.node_list:type_name -> lazygophers.lrpc.core.ServiceDiscoveryNode
	2,  // 4: lazygophers.lrpc.core.ServiceDiscoveryNode.type:type_name -> lazygophers.lrpc.core.ServiceType
	14, // 5: lazygophers.lrpc.core.ListOption.options:type_name -> lazygophers.lrpc.core.ListOption.Option
	17, // 6: lazygophers.lrpc.core.http:extendee -> google.protobuf.MethodOptions
	17, // 7: lazygophers.lrpc.core.lazygen:extendee -> google.protobuf.MethodOptions
	18, // 8: lazygophers.lrpc.core.port:extendee -> google.protobuf.FileOptions
	18, // 9: lazygophers.lrpc.core.host:extendee -> google.protobuf.FileOptions
	12, // 10: lazygophers.lrpc.core.http:type_name -> lazygophers.lrpc.core.Http
	13, // 11: lazygophers.lrpc.core.lazygen:type_name -> lazygophers.lrpc.core.LazyGen
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	10, // [10:12] is the sub-list for extension type_name
	6,  // [6:10] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	file_core_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		EnumInfos:         file_core_proto_enumTypes,
		MessageInfos:      file_core_proto_msgTypes,
		ExtensionInfos:    file_core_proto_extTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
